.\" Manpage for your script
.
.TH EasyVideo "1" "May 2022" "EasyVideo" "Manual"
.SH "NAME"
\fBEasyVideo\fR \-Video Converter
.
.SH SYNOPSIS
\fBEasyVideo\fR [\fB\-h help\fR] [\fB\-v version\fR]
.
.SH DESCRIPTION
Skrypt wykorzystuje FFmpeg 5.0 "Lorentz" w celu konwersji i modyfikacji plików wideo.
.br
Umożliwia też stworzenie nowych plików w innych formatach na podstawie załączonego pliku.
.br
Do okienkowej obsługi skryptu zostało użyte narzędzie YAD - Yet another dialog.
.br
Jest ono bardziej rozbudowane niż Zenity - pozwala na większą personalizację wyglądu okna
.br
i jego treści.
.br
Skrypt pozwala na:
.br
-zwykłą konwersję np. z formatu mp4 na mkv
.br
-kompresję poprzez zmniejszenie bitrate'u lub liczby klatek
.br
-zmianę wymiarów filmu np. zmianę z 4K na FHD
.br
[^powyższe opcje dostępne są jednocześnie]
.br
.br
Ponadto:
.br
-stworzenie nowego pliku wideo poprzez wycięcie fragmentu z zadanego pliku
.br
-stworzenie pliku audio poprzez wycięcie z filmu dźwięku
.br
-stworzenie pliku gif na podstawie przesłanego wideo
.br
-Wybór pliku odbywa się przez wskazanie go za pomocą okna.
.br
-Lokalizacja pliku wyjściowego może być domyślna (w miejscu w którym znajduje
.br
się oryginalny plik) lub też wybrana przez użytkownika.
.
.SH OPTIONS
-v wersja
.br
-h pomoc
.SH BUGS
blad przy konwersji na plik webm z bitrate > 512kbps
.br
inny blad - wyslij mail na ()
.SH AUTHOR
EasyVideo 1.0 - Created by Michał Tarnacki ()
.SH COPYRIGHTS
Licensed under GPL (see /usr/share/common-licenses/GPL for more details
.br
  or contact # the Free Software Foundation for a copy)
.SH SEE ALSO
man yad
.br
man ffmpeg
